/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdvisoriesRouteImport } from './routes/advisories'
import { Route as CheckSuspectRouteImport } from './routes/check-suspect'
import { Route as CitizenManualRouteImport } from './routes/citizen-manual'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CyberAwarenessRouteImport } from './routes/cyber-awareness'
import { Route as CyberVolunteersRouteImport } from './routes/cyber-volunteers'
import { Route as DailyDigestRouteImport } from './routes/daily-digest'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as GacAppealRouteImport } from './routes/gac-appeal'
import { Route as LearnCybercrimeRouteImport } from './routes/learn-cybercrime'
import { Route as LearningCornerRouteImport } from './routes/learning-corner'
import { Route as MediaGalleryRouteImport } from './routes/media-gallery'
import { Route as MyReportsRouteImport } from './routes/my-reports'
import { Route as NodalOfficersRouteImport } from './routes/nodal-officers'
import { Route as PublicNoticesRouteImport } from './routes/public-notices'
import { Route as ReportAbuseSocialMediaRouteImport } from './routes/report-abuse-social-media'
import { Route as ReportSuspectRouteImport } from './routes/report-suspect'
import { Route as SafetyTipsRouteImport } from './routes/safety-tips'
import { Route as TrackRouteImport } from './routes/track'
import { Route as TrainingResourcesRouteImport } from './routes/training-resources'
import { Route as WebsitePoliciesRouteImport } from './routes/website-policies'
import { Route as ReportSafetyRouteImport } from './routes/report/safety'
import { Route as ReportFinancialAboutYouRouteImport } from './routes/report/financial/about-you'
import { Route as ReportFinancialEvidenceRouteImport } from './routes/report/financial/evidence'
import { Route as ReportFinancialMoneyRouteImport } from './routes/report/financial/money'
import { Route as ReportFinancialSubmittedRouteImport } from './routes/report/financial/submitted'
import { Route as ReportFinancialSuspectRouteImport } from './routes/report/financial/suspect'
import { Route as ReportFinancialVerifyRouteImport } from './routes/report/financial/verify'
import { Route as ReportFinancialWhatHappenedRouteImport } from './routes/report/financial/what-happened'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisoriesRoute = AdvisoriesRouteImport.update({
  id: '/advisories',
  path: '/advisories',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckSuspectRoute = CheckSuspectRouteImport.update({
  id: '/check-suspect',
  path: '/check-suspect',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenManualRoute = CitizenManualRouteImport.update({
  id: '/citizen-manual',
  path: '/citizen-manual',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CyberAwarenessRoute = CyberAwarenessRouteImport.update({
  id: '/cyber-awareness',
  path: '/cyber-awareness',
  getParentRoute: () => rootRouteImport,
} as any)
const CyberVolunteersRoute = CyberVolunteersRouteImport.update({
  id: '/cyber-volunteers',
  path: '/cyber-volunteers',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyDigestRoute = DailyDigestRouteImport.update({
  id: '/daily-digest',
  path: '/daily-digest',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const GacAppealRoute = GacAppealRouteImport.update({
  id: '/gac-appeal',
  path: '/gac-appeal',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnCybercrimeRoute = LearnCybercrimeRouteImport.update({
  id: '/learn-cybercrime',
  path: '/learn-cybercrime',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningCornerRoute = LearningCornerRouteImport.update({
  id: '/learning-corner',
  path: '/learning-corner',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaGalleryRoute = MediaGalleryRouteImport.update({
  id: '/media-gallery',
  path: '/media-gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const MyReportsRoute = MyReportsRouteImport.update({
  id: '/my-reports',
  path: '/my-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const NodalOfficersRoute = NodalOfficersRouteImport.update({
  id: '/nodal-officers',
  path: '/nodal-officers',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicNoticesRoute = PublicNoticesRouteImport.update({
  id: '/public-notices',
  path: '/public-notices',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportAbuseSocialMediaRoute = ReportAbuseSocialMediaRouteImport.update({
  id: '/report-abuse-social-media',
  path: '/report-abuse-social-media',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportSuspectRoute = ReportSuspectRouteImport.update({
  id: '/report-suspect',
  path: '/report-suspect',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyTipsRoute = SafetyTipsRouteImport.update({
  id: '/safety-tips',
  path: '/safety-tips',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingResourcesRoute = TrainingResourcesRouteImport.update({
  id: '/training-resources',
  path: '/training-resources',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsitePoliciesRoute = WebsitePoliciesRouteImport.update({
  id: '/website-policies',
  path: '/website-policies',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportSafetyRoute = ReportSafetyRouteImport.update({
  id: '/report/safety',
  path: '/report/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportFinancialAboutYouRoute = ReportFinancialAboutYouRouteImport.update({
  id: '/report/financial/about-you',
  path: '/report/financial/about-you',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportFinancialEvidenceRoute = ReportFinancialEvidenceRouteImport.update({
  id: '/report/financial/evidence',
  path: '/report/financial/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportFinancialMoneyRoute = ReportFinancialMoneyRouteImport.update({
  id: '/report/financial/money',
  path: '/report/financial/money',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportFinancialSubmittedRoute =
  ReportFinancialSubmittedRouteImport.update({
    id: '/report/financial/submitted',
    path: '/report/financial/submitted',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReportFinancialSuspectRoute = ReportFinancialSuspectRouteImport.update({
  id: '/report/financial/suspect',
  path: '/report/financial/suspect',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportFinancialVerifyRoute = ReportFinancialVerifyRouteImport.update({
  id: '/report/financial/verify',
  path: '/report/financial/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportFinancialWhatHappenedRoute =
  ReportFinancialWhatHappenedRouteImport.update({
    id: '/report/financial/what-happened',
    path: '/report/financial/what-happened',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advisories': typeof AdvisoriesRoute
  '/check-suspect': typeof CheckSuspectRoute
  '/citizen-manual': typeof CitizenManualRoute
  '/contact': typeof ContactRoute
  '/cyber-awareness': typeof CyberAwarenessRoute
  '/cyber-volunteers': typeof CyberVolunteersRoute
  '/daily-digest': typeof DailyDigestRoute
  '/faq': typeof FaqRoute
  '/feedback': typeof FeedbackRoute
  '/gac-appeal': typeof GacAppealRoute
  '/learn-cybercrime': typeof LearnCybercrimeRoute
  '/learning-corner': typeof LearningCornerRoute
  '/media-gallery': typeof MediaGalleryRoute
  '/my-reports': typeof MyReportsRoute
  '/nodal-officers': typeof NodalOfficersRoute
  '/public-notices': typeof PublicNoticesRoute
  '/report-abuse-social-media': typeof ReportAbuseSocialMediaRoute
  '/report-suspect': typeof ReportSuspectRoute
  '/safety-tips': typeof SafetyTipsRoute
  '/track': typeof TrackRoute
  '/training-resources': typeof TrainingResourcesRoute
  '/website-policies': typeof WebsitePoliciesRoute
  '/report/safety': typeof ReportSafetyRoute
  '/report/financial/about-you': typeof ReportFinancialAboutYouRoute
  '/report/financial/evidence': typeof ReportFinancialEvidenceRoute
  '/report/financial/money': typeof ReportFinancialMoneyRoute
  '/report/financial/submitted': typeof ReportFinancialSubmittedRoute
  '/report/financial/suspect': typeof ReportFinancialSuspectRoute
  '/report/financial/verify': typeof ReportFinancialVerifyRoute
  '/report/financial/what-happened': typeof ReportFinancialWhatHappenedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advisories': typeof AdvisoriesRoute
  '/check-suspect': typeof CheckSuspectRoute
  '/citizen-manual': typeof CitizenManualRoute
  '/contact': typeof ContactRoute
  '/cyber-awareness': typeof CyberAwarenessRoute
  '/cyber-volunteers': typeof CyberVolunteersRoute
  '/daily-digest': typeof DailyDigestRoute
  '/faq': typeof FaqRoute
  '/feedback': typeof FeedbackRoute
  '/gac-appeal': typeof GacAppealRoute
  '/learn-cybercrime': typeof LearnCybercrimeRoute
  '/learning-corner': typeof LearningCornerRoute
  '/media-gallery': typeof MediaGalleryRoute
  '/my-reports': typeof MyReportsRoute
  '/nodal-officers': typeof NodalOfficersRoute
  '/public-notices': typeof PublicNoticesRoute
  '/report-abuse-social-media': typeof ReportAbuseSocialMediaRoute
  '/report-suspect': typeof ReportSuspectRoute
  '/safety-tips': typeof SafetyTipsRoute
  '/track': typeof TrackRoute
  '/training-resources': typeof TrainingResourcesRoute
  '/website-policies': typeof WebsitePoliciesRoute
  '/report/safety': typeof ReportSafetyRoute
  '/report/financial/about-you': typeof ReportFinancialAboutYouRoute
  '/report/financial/evidence': typeof ReportFinancialEvidenceRoute
  '/report/financial/money': typeof ReportFinancialMoneyRoute
  '/report/financial/submitted': typeof ReportFinancialSubmittedRoute
  '/report/financial/suspect': typeof ReportFinancialSuspectRoute
  '/report/financial/verify': typeof ReportFinancialVerifyRoute
  '/report/financial/what-happened': typeof ReportFinancialWhatHappenedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advisories': typeof AdvisoriesRoute
  '/check-suspect': typeof CheckSuspectRoute
  '/citizen-manual': typeof CitizenManualRoute
  '/contact': typeof ContactRoute
  '/cyber-awareness': typeof CyberAwarenessRoute
  '/cyber-volunteers': typeof CyberVolunteersRoute
  '/daily-digest': typeof DailyDigestRoute
  '/faq': typeof FaqRoute
  '/feedback': typeof FeedbackRoute
  '/gac-appeal': typeof GacAppealRoute
  '/learn-cybercrime': typeof LearnCybercrimeRoute
  '/learning-corner': typeof LearningCornerRoute
  '/media-gallery': typeof MediaGalleryRoute
  '/my-reports': typeof MyReportsRoute
  '/nodal-officers': typeof NodalOfficersRoute
  '/public-notices': typeof PublicNoticesRoute
  '/report-abuse-social-media': typeof ReportAbuseSocialMediaRoute
  '/report-suspect': typeof ReportSuspectRoute
  '/safety-tips': typeof SafetyTipsRoute
  '/track': typeof TrackRoute
  '/training-resources': typeof TrainingResourcesRoute
  '/website-policies': typeof WebsitePoliciesRoute
  '/report/safety': typeof ReportSafetyRoute
  '/report/financial/about-you': typeof ReportFinancialAboutYouRoute
  '/report/financial/evidence': typeof ReportFinancialEvidenceRoute
  '/report/financial/money': typeof ReportFinancialMoneyRoute
  '/report/financial/submitted': typeof ReportFinancialSubmittedRoute
  '/report/financial/suspect': typeof ReportFinancialSuspectRoute
  '/report/financial/verify': typeof ReportFinancialVerifyRoute
  '/report/financial/what-happened': typeof ReportFinancialWhatHappenedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advisories'
    | '/check-suspect'
    | '/citizen-manual'
    | '/contact'
    | '/cyber-awareness'
    | '/cyber-volunteers'
    | '/daily-digest'
    | '/faq'
    | '/feedback'
    | '/gac-appeal'
    | '/learn-cybercrime'
    | '/learning-corner'
    | '/media-gallery'
    | '/my-reports'
    | '/nodal-officers'
    | '/public-notices'
    | '/report-abuse-social-media'
    | '/report-suspect'
    | '/safety-tips'
    | '/track'
    | '/training-resources'
    | '/website-policies'
    | '/report/safety'
    | '/report/financial/about-you'
    | '/report/financial/evidence'
    | '/report/financial/money'
    | '/report/financial/submitted'
    | '/report/financial/suspect'
    | '/report/financial/verify'
    | '/report/financial/what-happened'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advisories'
    | '/check-suspect'
    | '/citizen-manual'
    | '/contact'
    | '/cyber-awareness'
    | '/cyber-volunteers'
    | '/daily-digest'
    | '/faq'
    | '/feedback'
    | '/gac-appeal'
    | '/learn-cybercrime'
    | '/learning-corner'
    | '/media-gallery'
    | '/my-reports'
    | '/nodal-officers'
    | '/public-notices'
    | '/report-abuse-social-media'
    | '/report-suspect'
    | '/safety-tips'
    | '/track'
    | '/training-resources'
    | '/website-policies'
    | '/report/safety'
    | '/report/financial/about-you'
    | '/report/financial/evidence'
    | '/report/financial/money'
    | '/report/financial/submitted'
    | '/report/financial/suspect'
    | '/report/financial/verify'
    | '/report/financial/what-happened'
  id:
    | '__root__'
    | '/'
    | '/advisories'
    | '/check-suspect'
    | '/citizen-manual'
    | '/contact'
    | '/cyber-awareness'
    | '/cyber-volunteers'
    | '/daily-digest'
    | '/faq'
    | '/feedback'
    | '/gac-appeal'
    | '/learn-cybercrime'
    | '/learning-corner'
    | '/media-gallery'
    | '/my-reports'
    | '/nodal-officers'
    | '/public-notices'
    | '/report-abuse-social-media'
    | '/report-suspect'
    | '/safety-tips'
    | '/track'
    | '/training-resources'
    | '/website-policies'
    | '/report/safety'
    | '/report/financial/about-you'
    | '/report/financial/evidence'
    | '/report/financial/money'
    | '/report/financial/submitted'
    | '/report/financial/suspect'
    | '/report/financial/verify'
    | '/report/financial/what-happened'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvisoriesRoute: typeof AdvisoriesRoute
  CheckSuspectRoute: typeof CheckSuspectRoute
  CitizenManualRoute: typeof CitizenManualRoute
  ContactRoute: typeof ContactRoute
  CyberAwarenessRoute: typeof CyberAwarenessRoute
  CyberVolunteersRoute: typeof CyberVolunteersRoute
  DailyDigestRoute: typeof DailyDigestRoute
  FaqRoute: typeof FaqRoute
  FeedbackRoute: typeof FeedbackRoute
  GacAppealRoute: typeof GacAppealRoute
  LearnCybercrimeRoute: typeof LearnCybercrimeRoute
  LearningCornerRoute: typeof LearningCornerRoute
  MediaGalleryRoute: typeof MediaGalleryRoute
  MyReportsRoute: typeof MyReportsRoute
  NodalOfficersRoute: typeof NodalOfficersRoute
  PublicNoticesRoute: typeof PublicNoticesRoute
  ReportAbuseSocialMediaRoute: typeof ReportAbuseSocialMediaRoute
  ReportSuspectRoute: typeof ReportSuspectRoute
  SafetyTipsRoute: typeof SafetyTipsRoute
  TrackRoute: typeof TrackRoute
  TrainingResourcesRoute: typeof TrainingResourcesRoute
  WebsitePoliciesRoute: typeof WebsitePoliciesRoute
  ReportSafetyRoute: typeof ReportSafetyRoute
  ReportFinancialAboutYouRoute: typeof ReportFinancialAboutYouRoute
  ReportFinancialEvidenceRoute: typeof ReportFinancialEvidenceRoute
  ReportFinancialMoneyRoute: typeof ReportFinancialMoneyRoute
  ReportFinancialSubmittedRoute: typeof ReportFinancialSubmittedRoute
  ReportFinancialSuspectRoute: typeof ReportFinancialSuspectRoute
  ReportFinancialVerifyRoute: typeof ReportFinancialVerifyRoute
  ReportFinancialWhatHappenedRoute: typeof ReportFinancialWhatHappenedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisories': {
      id: '/advisories'
      path: '/advisories'
      fullPath: '/advisories'
      preLoaderRoute: typeof AdvisoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-suspect': {
      id: '/check-suspect'
      path: '/check-suspect'
      fullPath: '/check-suspect'
      preLoaderRoute: typeof CheckSuspectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen-manual': {
      id: '/citizen-manual'
      path: '/citizen-manual'
      fullPath: '/citizen-manual'
      preLoaderRoute: typeof CitizenManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cyber-awareness': {
      id: '/cyber-awareness'
      path: '/cyber-awareness'
      fullPath: '/cyber-awareness'
      preLoaderRoute: typeof CyberAwarenessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cyber-volunteers': {
      id: '/cyber-volunteers'
      path: '/cyber-volunteers'
      fullPath: '/cyber-volunteers'
      preLoaderRoute: typeof CyberVolunteersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-digest': {
      id: '/daily-digest'
      path: '/daily-digest'
      fullPath: '/daily-digest'
      preLoaderRoute: typeof DailyDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gac-appeal': {
      id: '/gac-appeal'
      path: '/gac-appeal'
      fullPath: '/gac-appeal'
      preLoaderRoute: typeof GacAppealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn-cybercrime': {
      id: '/learn-cybercrime'
      path: '/learn-cybercrime'
      fullPath: '/learn-cybercrime'
      preLoaderRoute: typeof LearnCybercrimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning-corner': {
      id: '/learning-corner'
      path: '/learning-corner'
      fullPath: '/learning-corner'
      preLoaderRoute: typeof LearningCornerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media-gallery': {
      id: '/media-gallery'
      path: '/media-gallery'
      fullPath: '/media-gallery'
      preLoaderRoute: typeof MediaGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-reports': {
      id: '/my-reports'
      path: '/my-reports'
      fullPath: '/my-reports'
      preLoaderRoute: typeof MyReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodal-officers': {
      id: '/nodal-officers'
      path: '/nodal-officers'
      fullPath: '/nodal-officers'
      preLoaderRoute: typeof NodalOfficersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public-notices': {
      id: '/public-notices'
      path: '/public-notices'
      fullPath: '/public-notices'
      preLoaderRoute: typeof PublicNoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-abuse-social-media': {
      id: '/report-abuse-social-media'
      path: '/report-abuse-social-media'
      fullPath: '/report-abuse-social-media'
      preLoaderRoute: typeof ReportAbuseSocialMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-suspect': {
      id: '/report-suspect'
      path: '/report-suspect'
      fullPath: '/report-suspect'
      preLoaderRoute: typeof ReportSuspectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety-tips': {
      id: '/safety-tips'
      path: '/safety-tips'
      fullPath: '/safety-tips'
      preLoaderRoute: typeof SafetyTipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training-resources': {
      id: '/training-resources'
      path: '/training-resources'
      fullPath: '/training-resources'
      preLoaderRoute: typeof TrainingResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-policies': {
      id: '/website-policies'
      path: '/website-policies'
      fullPath: '/website-policies'
      preLoaderRoute: typeof WebsitePoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/safety': {
      id: '/report/safety'
      path: '/report/safety'
      fullPath: '/report/safety'
      preLoaderRoute: typeof ReportSafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/financial/about-you': {
      id: '/report/financial/about-you'
      path: '/report/financial/about-you'
      fullPath: '/report/financial/about-you'
      preLoaderRoute: typeof ReportFinancialAboutYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/financial/evidence': {
      id: '/report/financial/evidence'
      path: '/report/financial/evidence'
      fullPath: '/report/financial/evidence'
      preLoaderRoute: typeof ReportFinancialEvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/financial/money': {
      id: '/report/financial/money'
      path: '/report/financial/money'
      fullPath: '/report/financial/money'
      preLoaderRoute: typeof ReportFinancialMoneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/financial/submitted': {
      id: '/report/financial/submitted'
      path: '/report/financial/submitted'
      fullPath: '/report/financial/submitted'
      preLoaderRoute: typeof ReportFinancialSubmittedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/financial/suspect': {
      id: '/report/financial/suspect'
      path: '/report/financial/suspect'
      fullPath: '/report/financial/suspect'
      preLoaderRoute: typeof ReportFinancialSuspectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/financial/verify': {
      id: '/report/financial/verify'
      path: '/report/financial/verify'
      fullPath: '/report/financial/verify'
      preLoaderRoute: typeof ReportFinancialVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/financial/what-happened': {
      id: '/report/financial/what-happened'
      path: '/report/financial/what-happened'
      fullPath: '/report/financial/what-happened'
      preLoaderRoute: typeof ReportFinancialWhatHappenedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvisoriesRoute: AdvisoriesRoute,
  CheckSuspectRoute: CheckSuspectRoute,
  CitizenManualRoute: CitizenManualRoute,
  ContactRoute: ContactRoute,
  CyberAwarenessRoute: CyberAwarenessRoute,
  CyberVolunteersRoute: CyberVolunteersRoute,
  DailyDigestRoute: DailyDigestRoute,
  FaqRoute: FaqRoute,
  FeedbackRoute: FeedbackRoute,
  GacAppealRoute: GacAppealRoute,
  LearnCybercrimeRoute: LearnCybercrimeRoute,
  LearningCornerRoute: LearningCornerRoute,
  MediaGalleryRoute: MediaGalleryRoute,
  MyReportsRoute: MyReportsRoute,
  NodalOfficersRoute: NodalOfficersRoute,
  PublicNoticesRoute: PublicNoticesRoute,
  ReportAbuseSocialMediaRoute: ReportAbuseSocialMediaRoute,
  ReportSuspectRoute: ReportSuspectRoute,
  SafetyTipsRoute: SafetyTipsRoute,
  TrackRoute: TrackRoute,
  TrainingResourcesRoute: TrainingResourcesRoute,
  WebsitePoliciesRoute: WebsitePoliciesRoute,
  ReportSafetyRoute: ReportSafetyRoute,
  ReportFinancialAboutYouRoute: ReportFinancialAboutYouRoute,
  ReportFinancialEvidenceRoute: ReportFinancialEvidenceRoute,
  ReportFinancialMoneyRoute: ReportFinancialMoneyRoute,
  ReportFinancialSubmittedRoute: ReportFinancialSubmittedRoute,
  ReportFinancialSuspectRoute: ReportFinancialSuspectRoute,
  ReportFinancialVerifyRoute: ReportFinancialVerifyRoute,
  ReportFinancialWhatHappenedRoute: ReportFinancialWhatHappenedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
